/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author josue
 */
public class Interfaz extends javax.swing.JFrame {
    String usuarioActual;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    
    public void setUsuarioActual(String pUsuarioActual){
        this.usuarioActual=pUsuarioActual;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        chats = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnChatElectronica = new javax.swing.JButton();
        btnChatPop = new javax.swing.JButton();
        btnChatJazz = new javax.swing.JButton();
        btnChatClasica = new javax.swing.JButton();
        btnChatRock = new javax.swing.JButton();
        btnChatLatina = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Jazz");

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Rock");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chats.setBackground(new java.awt.Color(0, 51, 51));
        chats.setForeground(new java.awt.Color(255, 255, 255));
        chats.setToolTipText("Home");

        jToolBar1.setBackground(new java.awt.Color(2, 51, 19));
        jToolBar1.setRollover(true);
        chats.addTab("Home", jToolBar1);

        jToolBar2.setBackground(new java.awt.Color(2, 51, 19));
        jToolBar2.setRollover(true);
        chats.addTab("Buscar", jToolBar2);

        jToolBar3.setBackground(new java.awt.Color(2, 51, 19));
        jToolBar3.setRollover(true);
        chats.addTab("Cuenta", jToolBar3);

        jPanel1.setBackground(new java.awt.Color(2, 51, 19));

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(2, 51, 19));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mensajes directos", jPanel2);

        jPanel4.setBackground(new java.awt.Color(2, 51, 19));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chat temático");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciones un género para iniciar a chatear");

        btnChatElectronica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatElectronica.setText("Electrónica");
        btnChatElectronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatElectronicaActionPerformed(evt);
            }
        });

        btnChatPop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatPop.setText("Pop");
        btnChatPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatPopActionPerformed(evt);
            }
        });

        btnChatJazz.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatJazz.setText("Jazz");
        btnChatJazz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatJazzActionPerformed(evt);
            }
        });

        btnChatClasica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatClasica.setText("Clásica");
        btnChatClasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatClasicaActionPerformed(evt);
            }
        });

        btnChatRock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatRock.setText("Rock");
        btnChatRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatRockActionPerformed(evt);
            }
        });

        btnChatLatina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatLatina.setText("Latina");
        btnChatLatina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatLatinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnChatPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChatRock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChatElectronica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChatClasica, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChatJazz, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChatLatina, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChatRock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChatJazz, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChatElectronica, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChatClasica, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChatPop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChatLatina, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes temáticos", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        chats.addTab("Chats", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chats)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chats)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChatJazzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatJazzActionPerformed
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Jazz");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatJazzActionPerformed

    private void btnChatClasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatClasicaActionPerformed
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Clásica");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatClasicaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnChatRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatRockActionPerformed
        // TODO add your handling code here:
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Rock");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatRockActionPerformed

    private void btnChatLatinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatLatinaActionPerformed
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Latina");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatLatinaActionPerformed

    private void btnChatElectronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatElectronicaActionPerformed
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Electrónica");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatElectronicaActionPerformed

    private void btnChatPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatPopActionPerformed
        VentanaChat vNuevaVentanaChat = new VentanaChat();
        vNuevaVentanaChat.setNombreChat("Pop");
        vNuevaVentanaChat.setEmisor(usuarioActual);
        vNuevaVentanaChat.setVisible(true);
    }//GEN-LAST:event_btnChatPopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChatClasica;
    private javax.swing.JButton btnChatElectronica;
    private javax.swing.JButton btnChatJazz;
    private javax.swing.JButton btnChatLatina;
    private javax.swing.JButton btnChatPop;
    private javax.swing.JButton btnChatRock;
    private javax.swing.JTabbedPane chats;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
