/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Clases.HiloChatCliente;
import Clases.InstruccionChat;
import Clases.Mensaje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author 100da
 */
public class VentanaChat extends javax.swing.JFrame {
    private String nombreChat; //nombre de la persona remitente o nombre del tema
    private String emisor; //quien envia el mensaje
    private int tema;
    ///HiloChatCliente nuevoHiloCliente;
    /**
     * Creates new form VentanaChat
     */
    public VentanaChat() {
        initComponents();
        //nuevoHiloCliente = new HiloChatCliente(txaChat);
        
    }
    
    public void setNombreChat(String pNombreChat){
        this.nombreChat=pNombreChat;
        this.lblNombreChat.setText(pNombreChat);
    }
    
    public void setEmisor(String pEmisor){
        this.emisor=pEmisor;
        //JOptionPane.showMessageDialog(null, "desde seteo ya dentro de chat: "+this.emisor);
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enviarInstruccion();
            }
        });

        // Iniciar el temporizador
        timer.start();
        
    }
    
    public void setTema(int pTema){
        this.tema=pTema;
        
    }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreChat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaChat = new javax.swing.JTextArea();
        txtNuevoMensaje = new javax.swing.JTextField();
        btnEnviarMensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 51, 19));

        lblNombreChat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreChat.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreChat.setText("nombre de chat");

        txaChat.setColumns(20);
        txaChat.setRows(5);
        jScrollPane1.setViewportView(txaChat);

        txtNuevoMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoMensajeActionPerformed(evt);
            }
        });

        btnEnviarMensaje.setText("Enviar");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreChat)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNuevoMensaje)
                            .addGap(18, 18, 18)
                            .addComponent(btnEnviarMensaje))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblNombreChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNuevoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        // TODO add your handling code here:
        Mensaje vNuevoMensaje = new Mensaje();
        vNuevoMensaje.setContenido(txtNuevoMensaje.getText());
        vNuevoMensaje.setEmisor(this.emisor);
        vNuevoMensaje.setTema(tema);
        txtNuevoMensaje.setText(""); 
        
        Socket vNuevoSocket;
        
        try {
            vNuevoSocket = new Socket("127.0.0.1", 15575);
            ObjectOutputStream vSerializador = new ObjectOutputStream(vNuevoSocket.getOutputStream());
            vSerializador.writeObject(vNuevoMensaje); // issue del lado del servidor, agregar instanceOf para recibir un objeto de tipo Mensaje
            vSerializador.close();
            vNuevoSocket.close();
            
        } catch (IOException ex) {
            Logger.getLogger(VentanaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //nuevoHiloCliente.detener();
    }//GEN-LAST:event_formWindowClosed

    private void txtNuevoMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoMensajeActionPerformed

    private void enviarInstruccion(){
        InstruccionChat vNuevaInstruccion = null;
        if (tema!=0) {
            vNuevaInstruccion = new InstruccionChat(this.emisor, this.tema);
        }else{
            vNuevaInstruccion = new InstruccionChat(this.emisor, this.nombreChat);
        }

        try {
            Socket vSocket = new Socket("127.0.0.1", 15575);
            ObjectOutputStream vSerializador = new ObjectOutputStream(vSocket.getOutputStream());
            ObjectInputStream vDeserializador = new ObjectInputStream(vSocket.getInputStream()); 
            
            vSerializador.writeObject(vNuevaInstruccion);
            vSerializador.flush();
            
            //vSocket.setSoTimeout(1);
            Object resultado=null;
            ArrayList<Mensaje> listaMensajes = new ArrayList();
            try{
                resultado = vDeserializador.readObject();
                listaMensajes = (ArrayList<Mensaje>) resultado;
                txaChat.setText("");
                for (Mensaje mensaje : listaMensajes) {
                    txaChat.append("["+mensaje.getEmisor()+"]: ");
                    txaChat.append(mensaje.getContenido()+"\n");
                }
            } catch (SocketTimeoutException e) {}
            
            
            vSerializador.close();
            vDeserializador.close();
            ///vDeserializador.close();
            vSocket.close();

            
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VentanaChat.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreChat;
    private javax.swing.JTextArea txaChat;
    private javax.swing.JTextField txtNuevoMensaje;
    // End of variables declaration//GEN-END:variables
}
